
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Sync dev dependencies
        run: uv sync --group dev

      - name: Lint with ruff
        run: uv run --group dev ruff check --output-format=github .

      - name: Format check with ruff
        run: uv run --group dev ruff format --check .

      - name: Test with pytest
        run: uv run --group dev pytest -q

  release-please:
    needs: build-and-test
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          release-type: python
          package-name: ssh-connector
